### ISSUE TITLE
Missing scripts

### ISSUE THREAD

**Issue by wilkersonrdevon** [RevOcelotMGS/Marrow-ExtendedSDK#7]
I followed the instructions twice and so far nothing seems to fix this issue. Image attached is the problem. The scripts are there, just not being recognized by Unity. 
![Screenshot 2022-10-23 164804](https://user-images.githubusercontent.com/75996512/197417524-e81f90a5-d634-44a9-88a4-80397d998e27.png)

**Comment by RevOcelotMGS** [comment]
If you haven't already, try to give the meta file updater a shot. Otherwise, repeat the package installation steps to see if that solves the issue.

**Comment by wilkersonrdevon** [comment]
> If you haven't already, try to give the meta file updater a shot. Otherwise, repeat the package installation steps to see if that solves the issue.

Where is the meta file updater located?

**Comment by wilkersonrdevon** [comment]
![image](https://user-images.githubusercontent.com/75996512/197827454-469c97be-e850-4da9-9acd-3c3d45694953.png)
I completely missed this repo, I thought they were the same three from the official sdk. Works fine now.

**Comment by dotbenj** [comment]
If you are all good can you close the issue?
